#!/usr/bin/env php
<?php
set_time_limit(0);
require_once __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use SDPHP\HangMan\HangManCommand;

$application = new Application();
$application->add(new HangManCommand());
$application->run();